post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iml0YWxvIiwiaWQiOiI1ZDg0OGYzYzdkZTAyNzM1MTgwYzZkZWIiLCJpYXQiOjE1Njg5Njg1MTR9._tpVOxVCU_QtJLzQwcxc9duTBnsU9OfE8s4Lj3DkkGc

{
  "title": "To Be Deleted 1",
  "author": "by Italo",
  "url": "cannata.com",
  "likes": 1
}